### ISSUE TITLE
disabilitare e abilitare corse h12 in rc1.1

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/meteomixer#18]
Siamo ancora alle prese con la review della #7 

A fronte di una serie di cambiamenti nel postprocessing sarebbe comunque il caso di mettere in produzione la rc1.1 nell'attesa di aggiustare il postprocessing della corsa delle 12.

L'ipotesi più grezza è sospendere la produzione dei dati in modo che non risultino disponibile.
Se ci fosse un modo di nasconderle a livello di interfaccia (non necessariamente con una conf, anche con una commit facilmente reversibile) intanto mandiamo in produzione la nuova versione.

**Comment by spanezz** [comment]
In `mmlib/product.py:202` ho aggiunto (e testato!) queste righe

```py
            if product.run.model.name == "ExampleModel" and product.run.reftime.hour == 12:
                continue
```

Puoi provare se basta saltare il detect dell'output dei modelli che non vuoi agendo su quelle due righe?

**Comment by brancomat** [comment]
Ci ho provato nella nostra istanza di test ma purtroppo non funziona (vedo ancora tutte le corse).

Riesci a dare un'occhiata alla nostra istanza di test o darmi qualche estremo per un debug? (al momento è allineata al branch rc1.1 tranne per la modifica a quella riga dove ho tolto dall'if il `product.run.model.name` lasciando solo il test su `product.run.reftime.hour == 12`

lo trovi su:
`meteomixer@meteomixe8:/home/meteomixer/meteomixer/mmlib`

**Comment by spanezz** [comment]
I pushed another possible skipping place in f24cbe5b937fd3dcd267f66a084c53d14529d71a: look into `monitor/models.py:64`.

Note that the results are cached in the session, so if you have a session currenly open, you won't see any difference after deploying the change. Close/abort the current session and restart it, and the run should be gone. This is because meteomixer ignores the actual state of things for an existing session, so that you could inspect, for example, a session from one year ago which was potentially run with a completely different set of models than one'd have now.

I could unfortuanately not test it on `meteomixer8` because I didn't want to potentially close/abort the existing session

**Comment by brancomat** [comment]
Funziona!
Giusto per tener traccia: al momento sto utilizzando entrambi gli `if` a mo' di toggle per la visualizzazione delle corse delle  12:
`monitor/models.py:64`
`mmlib/product.py:202`
